### ISSUE TITLE
Comunicaciones

### ISSUE THREAD

**Issue by JuanCruzMz** [RobertaGabor/TP_SO_i1_110#1]

**Comment by JuanCruzMz** [comment]
Hola? Un, dos, tres, probando...

**Comment by JuanCruzMz** [comment]
Compañeras?

**Comment by RobertaGabor** [comment]
hola, decia que queria cambiar nombre antes de que todos comitearan pero bueno jaja

**Comment by costanzoabril** [comment]
ya fue no creo que le moleste

**Comment by costanzoabril** [comment]
que lo vea a ver si vamos bien no?

**Comment by JuanCruzMz** [comment]
Uy, no me di cuenta lo del nombre

**Comment by JuanCruzMz** [comment]
Roberta, yo veo el primer commit tuyo con tu nombre

**Comment by JuanCruzMz** [comment]
Y el resto con "Your Name". Que raro

**Comment by RobertaGabor** [comment]
sisi porque el primero lo hice desde github

**Comment by RobertaGabor** [comment]
ahi lo cambie igual por ahora

**Comment by RobertaGabor** [comment]
se ve?

**Comment by JuanCruzMz** [comment]
Ahí me fijo

**Comment by costanzoabril** [comment]
sii, ahora quedo con tu nombre

**Comment by JuanCruzMz** [comment]
Con el "git log" me sale igual que antes. 
Donde era que se podía ver en el repo?

**Comment by costanzoabril** [comment]
igual el anterior quedo con your name pero no importa

**Comment by RobertaGabor** [comment]
si ya fue, el sabe ajja despues voy a intentar logear con el user de windows y veo

**Comment by JuanCruzMz** [comment]
Ah, xcelente entonces

**Comment by RobertaGabor** [comment]
ahi contesto y pusheo

**Comment by JuanCruzMz** [comment]
Dale. Sin apuro igual, tenemos una semana :D

**Comment by RobertaGabor** [comment]
listo! uff

**Comment by JuanCruzMz** [comment]
A nosotros no nos dijo nada todavía, así que vamos bien jaja

**Comment by costanzoabril** [comment]
listo juann

**Comment by costanzoabril** [comment]
corregime la respuesta C que me falto un espacio xd

**Comment by JuanCruzMz** [comment]
Estaba haciendo justo eso jajaja

**Comment by JuanCruzMz** [comment]
Listoo

**Comment by RobertaGabor** [comment]
buenisimoo

**Comment by JuanCruzMz** [comment]
Justo a tiempo para el final de la clase xD

**Comment by costanzoabril** [comment]
hola

**Comment by costanzoabril** [comment]
banquenme que lo hago devuelta xq no me puse el numero del equipo

**Comment by JuanCruzMz** [comment]
Ok

**Comment by JuanCruzMz** [comment]
Ya está mi parte

**Comment by JuanCruzMz** [comment]
Perdonen la tardanza. Mi maquina decidió que era buen momento para tener un infarto, y encima después la consola me empezó a tirar un monton de errores... un desastre
